Feature/pve role
lae/ansible-role-proxmox pull request #110
Opened 2020-12-08 17:11 UTC by trickert76

I've added a new module for managing pve roles (because Icinga monitoring user needs a special role and I don't want to add it manually on all clusters). I was able to create and remove a role.

2020-12-08 17:27 UTC, lae requested changes
Overall looks good to me.

When you're making changes after reviewing my comments, can you squash all your commits into one commit and force push that?

2020-12-08 17:27 UTC, lae commented on library/proxmox_role.py
> +          updated_fields.append(key)
I think the way this is written always results in updated fields, given `prepare_role_args()` parses the task values every time? Is there supposed to be a comparison to `existing_role` here?

2020-12-08 17:27 UTC, lae commented on library/proxmox_role.py
> +def main():
need newline here

2020-12-08 17:27 UTC, lae commented on defaults/main.yml
> +---
not sure if this might irritate the linter. if it doesn't complain, then it's fine.

2020-12-08 17:27 UTC, lae commented on tasks/main.yml
> +  when: "not pve_cluster_enabled | bool or (pve_cluster_enabled | bool and inventory_hostname == groups[pve_group][0])"
These changes should preferably be done in a separate PR as they're not associated with this feature.

2020-12-08 17:34 UTC, lae commented on defaults/main.yml
> +---
just checked, looks like it doesn't

2020-12-10 10:18 UTC, trickert76 commented on defaults/main.yml
> +---
actually - this should be "normal". Everything above --- is a header and must be commented. It is designed in YAML to contain a description, author ets. My personal project with ansible roles runs agains ansible-lint and yamllint and that is ok.

2020-12-10 10:18 UTC, trickert76 commented on tasks/main.yml
> +  when: "not pve_cluster_enabled | bool or (pve_cluster_enabled | bool and inventory_hostname == groups[pve_group][0])"
ok

2020-12-10 10:20 UTC, trickert76 commented on library/proxmox_role.py
> +          updated_fields.append(key)
Yes, thats right. I'm still working on it.

2020-12-10 10:20 UTC, trickert76 commented on library/proxmox_role.py
> +def main():
done

2020-12-10 11:04 UTC, trickert76 commented
> Overall looks good to me.
> 
> When you're making changes after reviewing my comments, can you squash all your commits into one commit and force push that?

Can you give me a hint, how to do that? I'm finished now. The proxmox_role works.

2020-12-10 11:15 UTC, lae commented
Have a read through the following article:

https://gitbetter.substack.com/p/how-to-squash-git-commits

You can run `git rebase -i develop` for an easy way to start off from the develop branch. Leave the first commit as pick, change the rest to squash. You should remove any of the extraneous commit messages when you're editing the final commit message so that it's succinct and describes the end result (e.g. the final commit history won't have the eclipse settings file, so there shouldn't be a mention of it).

Once you've squashed those commits into one, use `git push -f` to overwrite the remote branch (on github) and this PR will reflect that change automatically.

2020-12-10 11:24 UTC, lae commented on library/proxmox_role.py
> +                    old_value = str(old_value.sort())
`sort()` doesn't return the contents of the list here. You'd need to sort it separately and then use `old_value`/`new_value`.  (I'm also not sure why `str()` is being used here instead of like, `join()`.)

2020-12-10 11:48 UTC, trickert76 commented on library/proxmox_role.py
> +                    old_value = str(old_value.sort())
Ah, you're right. That code is irrelevant. The value is always a string.

2020-12-10 12:49 UTC, closed without merging

2020-12-10 12:50 UTC, trickert76 commented
I'm to stupid for squashing - i tried different ways but at the end there are always just new commits to origin. So I'll open a new PR with a fresh branch