Add Proxmox Backup Server storage type
lae/ansible-role-proxmox pull request #169
Opened 2021-10-19 11:42 UTC by lae

Closes #163

Possibly some stuff missing, actually. I have some changes for `prune-backups` stashed currently because I need to write more parsing logic around it so I'm putting that off because it seems like it's optional (it's not mentioned in https://pve.proxmox.com/wiki/Storage:_Proxmox_Backup_Server) and applies to storages in general (so I'll work on it separately later). The `encryption-key` JSON might require further validation, but I have no idea what it's supposed to look like.

This isn't being added to the test environment since PVE apparently does try to contact PBS during creation and we obviously can't set up a test PBS instance just for this. However, I think that might only be if it's set to `autogen`? So maybe it'll skip contacting PBS if valid JSON is provided (and thus we could try to implement a test that way).

2022-01-17 16:01 UTC, alexschomb commented
Hi,

I did some thorough testing of your commits and can confirm that it partly works.

I had to remove anything related to ``master_pubkey`` from the code because I always received the following error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'ProxmoxStorage' object has no attribute 'master_pubkey'
```

As a result, I expect ``encryption_key`` to be broken, and it doesn't seem to work at all. In #163 you asked for the format of such ``encryption_key`` and I am happy to provide you with an example of an automatically generated key:

```{"kdf":null,"created":"2022-01-17T16:55:00+01:00","modified":"2022-01-17T16:55:00+01:00","data":"a59lqYGkPJO2gRq3buHscIfAoLJsztG+ZBn7CaUQ0yM=","fingerprint":"6c:c2:1a:1e:f7:65:cf:ce:2a:ed:4e:b8:7a:5e:3d:b3:36:9c:fa:6b:da:2e:4b:02:dd:16:2e:b1:1f:ec:8b:e3"}```

With ``master_pubkey`` traces removed, no ``encryption_key`` variable set and ``fingerprint`` provided, the task works just fine and successfully adds the ``pbs`` type storage to the PVE host.

But with PVE/PBS it is also possible to add a new ``pbs`` storage without providing any fingerprint. This requires the PBS server to have a signed certificate, which can effortlessly be provided with Let's Encrypt. Unfortunately the Ansible role task fails with the following error message if no fingerprint is given:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: expected string or bytes-like object failed
```

2023-03-07 09:52 UTC, user1007017 commented
> Unfortunately the Ansible role task fails with the following error message if no fingerprint is given:
> 
> ```
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: expected string or bytes-like object failed
> ```


Seems there is an error validating the fingerprint which causes the creation of other stores to fail - 
if you comment out the 3 lines in the following snippet in proxmox_storage.py it runs until the end

 ```
 # Validate the parameters given to us
        fingerprint_re = re.compile('^([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}$')
        # if not fingerprint_re.match(self.fingerprint):
            # self.module.fail_json(msg=(f"fingerprint must be of the format, "
                                    #    f"{fingerprint_re.pattern}."))
```

2023-07-28 11:01 UTC, Andre15711 requested changes

2023-07-28 11:43 UTC, lae commented on library/proxmox_storage.py
> +        if not fingerprint_re.match(self.fingerprint):
fixed

2023-07-28 11:45 UTC, lae commented
Rebased against develop and fixed the logic issue with the fingerprint param. Can someone test this for me? Will merge afterwards.

2023-09-01 16:31 UTC, merged