feature/vfio-support
lae/ansible-role-proxmox pull request #202
Opened 2022-08-15 21:05 UTC by deloa6133

Added basic support for PCIe Passthrough using Intel or AMD based CPU's.
Feature is disabled by default as to prevent breaking change. Mediated
devices are supported, however, this is a modifiable attribute since not
all devices support gtv-g. IOMMU unsafe interupts are not necessary but
can be beneficial so support was added for that as well.

2022-08-18 10:03 UTC, lae commented
I see you've updated the role variable names, cool. Asides from that, can you enable this for the tests in `tests/`? Mainly need it for `tests/vagrant/` as I haven't gotten around to fixing/re-enabling CI. I'll do a further review when I can.

2022-08-18 20:07 UTC, deloa6133 commented
As this is the first time I have used Vagrant, I messaged on Discord for help if you don't mind :)

2022-08-18 21:17 UTC, lae requested changes
This is a good start. Most of the requested changes are either for consistency or because `ansible-lint` gave a failure.

In addition to these changes, `kernel_module_cleanup.yml` should also be updated to add steps to cleanup changes when any of these role variables are unset or set to false. You can take a look at how it's done for other modules and mimick it for the most part.

2022-08-18 21:17 UTC, lae commented on tasks/pcie-passthrough.yml
> +    when: iommu_modify.changed
Should be "iommu_modify is changed" to pass lint checker.

2022-08-18 21:17 UTC, lae commented on tasks/pcie-passthrough.yml
> +---
This file was named `pcie-passthrough.yml` but `pcie_passthrough.yml` is what is being included in `tasks/main.yml`. This file should be renamed with an underscore instead of hyphen.

2022-08-18 21:17 UTC, lae commented on tasks/pcie-passthrough.yml
> +  - name: Enable CPU IOMMU in default grub
Tasks need to be indented by four spaces in a block, not two.

2022-08-18 21:17 UTC, lae commented on tasks/pcie-passthrough.yml
> +  ansible.builtin.lineinfile:
Use `ansible.builtin.copy` for this https://github.com/lae/ansible-role-proxmox/blob/v1.7.1/tasks/ipmi_watchdog.yml#L11 and specify the mode (0640 is fine)

2022-08-18 21:17 UTC, lae commented on tasks/pcie-passthrough.yml
> +    command: update-initramfs -u -k all
Change to `ansible.builtin.command`

2022-08-23 19:37 UTC, lae commented
Sorry for the late follow-up, I'm busy and haven't gotten a chance to run tests (takes forever) and just test it out in general, but this is on my radar and I'll let you know when I can.

There was one thing I was wondering whether or not to point out, but since it's probably gonna take me a while to actually get to this, I might as well. A lot of folks looking for VFIO in Proxmox are likely wanting it for their GPU(s), and in most cases that requires stubbing the GPU's vendor/product ID so that drivers don't try to drive them on the host. This PR is missing that and I was thinking it *could* be a separate follow-up PR, but since I think most folks need it anyway it could also be part of this one. It is explained in the PVE wiki a bit: https://pve.proxmox.com/wiki/Pci_passthrough#GPU_Passthrough

It may not be the best explanation (in fact, https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Isolating_the_GPU is a better read), but as a real-world example this is my Proxmox workstation that I rely on to passthrough GPUs and USB controllers:

```
~$ cat /etc/modprobe.d/vfio.conf
softdep amdgpu pre: vfio-pci
softdep radeon pre: vfio-pci
options vfio-pci ids=1002:67df,1002:aaf0,1b73:1100,1002:6981,1002:aae0,1002:73e3 disable_vga=1
~$ grep vfio /etc/default/grub
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX amd_iommu=on iommu=pt vfio-pci.ids=1002:67df,1002:aaf0,1b73:1100,1002:6981,1002:aae0,1002:73e3 pci.stub.ids=1002:67df,1002:aaf0,1002:6981,1002:aae0,1002:73e3"
```

Think adding a role variable+task for another `GRUB_CMDLINE_LINUX` line could work?

2022-08-24 01:53 UTC, deloa6133 commented
Yes another line could handle this, I can take a look into it a bit more since I have not really had experience with dedicated GPU passhthrough, only integrated devices. I know this could require modifying/creating blacklists for drivers as well depending on device vendor/use case. Either way I can look into it a bit and possibly branch off of this PR to see if I can get something working properly

2022-08-24 09:49 UTC, lae commented
I don't think we have to worry too much about trying to cater to specific vendors in particular. Just having the user specify IDs and what drivers to use softdep on (I guess this is an alternative to actually blacklisting them) would get us most of the way, and if the user needs to do something else they can probably just add it to their playbook.

2022-08-24 19:57 UTC, deloa6133 commented
Enabled pci id and driver vars that can configure default grub and vfio.conf file for gpu and other device passthrough. I think at this point a separate section in the README for `PCIe Passthrough:` would be appropriate to help people understand more in depth how this works. I'll write something up for that

2022-10-04 23:17 UTC, lae commented
I'll be available to review this properly mid-Oct. Please remind me then if I haven't.

2022-10-27 23:28 UTC, ol3d commented
Reminder to take a look into this PR more in depth

2023-05-18 21:33 UTC, ol3d commented
Closing due to inactivity, may re-open in the future

2024-07-02 16:53 UTC, ol3d commented
Apologies for the large amount of commits. Testing was done in my homelab and pulled from the repo instead of hosting the role locally. Over an extended peroid of time many changes/improvements were made. Everything should be current as of now. There are future enhancements I would like to add, however, I wanted to get this out for now for review.

2024-07-02 18:47 UTC, closed without merging