fix: set noninteractive for apt upgarde
lae/ansible-role-proxmox pull request #246
Opened 2024-06-29 16:35 UTC by jeschero

Hey,

I have a little fix here that fixes the `apt upgrade` not waiting for user input anymore.
Otherwise it can happen that during `apt upgarde` apt will ask user something and since these are not answered in ansible, an error is generated.

Regards
jeschero

2024-07-01 21:32 UTC, lae commented
Should this be applied to all apt tasks or just the `dist-upgrade` one?

2024-07-06 23:46 UTC, edv-pi commented
to all apt tasks, theres no reason to use dialog for apt when run through ansible.

2024-07-06 23:49 UTC, edv-pi approved these changes

2024-07-07 02:03 UTC, lae commented
I am questioning whether this change does what it is intended to do. The `apt` module already seems to have this set:

https://github.com/ansible/ansible/blob/v2.17.1/lib/ansible/modules/apt.py#L1248

@jeschero Can you provide debug output for whatever playbook run was failing for you prior to making this change?

2024-07-07 02:08 UTC, lae requested changes

2024-07-07 02:08 UTC, lae commented on tasks/main.yml
> +    - "DEBIAN_FRONTEND: noninteractive"
Syntax is off, anyway.

https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_environment.html#setting-the-remote-environment-in-a-task

2024-07-07 12:06 UTC, edv-pi commented
ah lol, nice to know, didnt notice they added that

2024-07-07 12:23 UTC, lae commented
You're right that there's no reason for not using dialog when running apt through ansible, so I assumed that the module itself would already have disabled it in the first place instead of expecting users of the module to provide that env variable. And [it has been in ansible for 12 years](https://github.com/ansible/ansible-modules-core/commit/72aefdb609a16fa55903939b210d215f48925d75), apparently.

2024-07-10 01:46 UTC, closed without merging