Support for CIFS storages, namespacing in PBS, and ranking interfaces for corosync
lae/ansible-role-proxmox pull request #251
Opened 2024-07-07 00:54 UTC by edv-pi

I added CIFS support and the new feature from pbs for namespaces so that it is possible to mount pbs namespaces with pve_cluster_prio0 and pve_cluster_prio1 it is possible to define which link has the higher priority.

2024-07-07 01:44 UTC, lae requested changes
Thanks for the history cleanup.

In addition to the comments, can you add documentation for the new role variables as well as the CIFS storage support (this should go under `Storage Management`) to the README?

Also, I'm not sure what value is supported to go into `pve_cluster_prio0` etc (documentation should help here), but if I'm assuming correctly that it's an integer for ranking that particular interface, then I *think* `pve_cluster_prio0` etc should really be `pve_cluster_addr0_priority` (and same for `prio1`), otherwise it gives me the impression that `prio0` is yet another interface and not associated to `addr0`.

2024-07-07 01:44 UTC, lae commented on defaults/main.yml
> +no_logging: false
Role variable should be prefixed with `pve_`. Given how this variable is used, I'd probably just use `pve_no_log` instead of `pve_no_logging`.

2024-07-07 01:44 UTC, lae commented on library/proxmox_storage.py
> +    content: ["snippets", "vztmpl", "iso" ]
needs a space before `"snippets"`

2024-07-07 01:44 UTC, lae commented on library/proxmox_storage.py
> +  proxmox_Storage:
storage should not be capitalized

2024-07-07 01:44 UTC, lae commented on library/proxmox_storage.py
> -
newline should be kept (and after your inserts/before the `# Validate ...` comment), it's here for readability.

2024-07-07 01:44 UTC, lae commented on library/proxmox_storage.py
> -
Keep newline before `return` statement.

2024-07-07 01:44 UTC, lae commented on library/proxmox_storage.py
> +                           "zfspool", "btrfs", "pbs","cifs"]),
Needs space after comma.

2024-07-07 01:44 UTC, lae commented on library/proxmox_storage.py
> +
Remove newline.

2024-07-07 01:44 UTC, lae commented on tasks/main.yml
> +# Set logging to true in production in ypur groupvars
This comment can be left out, or rather moved into the documentation.

2024-07-07 01:44 UTC, lae commented on tasks/main.yml
> +  no_log: "{{ no_logging | default(false) }}"
`default(false)` is redundant here as it's already specified in a defaults file. Should remove it and update the role variable to the new name.

2024-07-07 01:44 UTC, lae commented on tasks/pve_add_node.yml
> +    -link0 {{ pve_cluster_addr0 }},priority={{ pve_cluster_prio0 | default(omit)}}
`default(omit)` I believe breaks here? It's meant for omitting certain attributes of a module and is meant to be the only value in the attribute field, e.g.

```yaml
ansible.builtin.module:
  attribute: "{{ some_var | default(omit) }}"
```

IIRC technically this sets `attribute` to something like `omit-randomhash` and Ansible interprets this to ignore the attribute. The way it's being used here, I believe it'll just insert something like `-link0 1.2.3.4,priority=omit-e52bf6d0bf43` and use that as-is.

Either way, it looks like what you want to do is omit the `priority` value anyway but that's hardcoded into the string so it wouldn't be left out in the first place. This should be something like `-link0 {{ pve_cluster_addr0 }}{{ ",priority=" + pve_cluster_prio0 if pve_cluster_prio0 is defined }}`, but I'm not sure if this is valid syntax in Ansible's Jinja2 templates. `{% if pve_cluster_prio0 is defined %},priority={{ pve_cluster_prio0 }}{% endif %}` is a bit longer but should work I think, if the other one doesn't.

2024-07-07 12:22 UTC, edv-pi commented on library/proxmox_storage.py
> -
added the newline but github seems not to detect the change :/

2024-07-09 23:52 UTC, lae approved these changes
Weird that the PVE docs doesn't mention namespaces (it's a valid flag, just seems undocumented).
https://github.com/proxmox/pve-docs/blob/f5e17ae1c680a475e980230d4d96a36db2c7afcd/pve-storage-pbs.adoc

Anyway, I added some additional changes since there were inconsistencies. Also for future reference, links don't work in code blocks (so the one for priority was invisible in the generated document).

2024-07-09 23:53 UTC, merged