Metric Servers management in Proxmox
lae/ansible-role-proxmox pull request #262
Opened 2024-08-30 17:39 UTC by thystips

Tested only with PVE 7

Telegraf can be used to transfert metrics to Prometheus, Elasticsearch, etc.

Resolve #259

2024-08-30 21:17 UTC, lae requested changes
Overall very well done. Thanks for the PR!

There's one critical change needed (the imports) and I've left comments for some other things.

2024-08-30 21:17 UTC, lae commented on library/proxmox_metric_server.py
> +            self.existing_server = pvesh.get("cluster/metrics/server")
minor nitpick, but pluralize var?

2024-08-30 21:17 UTC, lae commented on library/proxmox_metric_server.py
> +        self.servers = []
unused variable

2024-08-31 00:42 UTC, lae commented
oh, feel free to add your name to the list of contributors for metric server configuration support. (otherwise I'll add it later)

2024-08-31 14:40 UTC, thystips commented
I initially write this module for a private collection where this module is used as standalone after proxmox install, I forgot edit some code like import. It' s fixed.
All requests solved.

2024-09-01 10:37 UTC, lae approved these changes

2024-09-01 10:37 UTC, lae commented on library/proxmox_metric_server.py
> +    if module.params["type"] == "graphite" and any(
I'm assuming it's intentional, but the conditions in this statement slightly changed ( `a || b && c` → `a || b || c` ).

2024-09-01 10:37 UTC, merged

2024-09-01 10:58 UTC, thystips commented on library/proxmox_metric_server.py
> +    if module.params["type"] == "graphite" and any(
Yes it is intentional. Graphite have less arguments in API.